version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - pip3 install awscli --upgrade --user
  build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${CODEARTIFACT_DOMAIN} --query authorizationToken --output text`
      - echo $env.CODEARTIFACT_AUTH_TOKEN
      - mvn -s settings.xml clean package deploy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-boot-openapi-generator-tutorial-1.0.0-SNAPSHOT.jar
